### ISSUE TITLE
这个和原版有什么区别？

### ISSUE THREAD

**Issue by Nakasu-ksm** [mediv01/NotepadPro#1]
这个和原版有什么区别？
单纯只是删除言论，替换logo，更换开源地址吗，修改作者信息吗？？

**Comment by mediv01** [comment]
还有就是作者说后续会加入恶意改代码的功能，后面我控制的版本会保证这部分代码被剔除。

**Comment by BlackieVan** [comment]
没有安装包版本嘛？便携版好像缺一些右键菜单什么的
